### ISSUE TITLE
Maplist with personal record should display record position

### ISSUE THREAD

**Issue by TheMaximum** [ManiaJS/plugins#6]
How to get the position in the recordlist without getting the complete recordlist for all maps...?

**Comment by tomvlk** [comment]
Sequelize can count the rows.

So you can find all rows(records) that are faster than the current record time. Then order on the times in database. And count the rows that are above the current driven time.

(http://docs.sequelizejs.com/en/latest/api/model/#countoptions-promiseinteger)
